[package]
name = "native-ts-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itoa = "^1.0"
dtoa = "^1.0"
byteorder = { version = "^1", default-features = false }

parking_lot = "*"
